version: "3.8"

name: "auction-bird"
services:
  client:
    container_name: client
    build:
      context: ./Presentation/ClientApp
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./Presentation/ClientApp:/app
      - /app/node_modules
    networks:
      - ab_network
  
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Presentation/Dockerfile
      target: development
    env_file:
      - ./Presentation/env/server.env
    depends_on:
      - database
      - redis
    ports:
      - "8080:8080"
    networks:
      - ab_network
  
  logger:
    container_name: logger
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "8081:80"
    networks:
      - ab_network
        
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    env_file:
      - ./Presentation/env/redis.env
    ports:
      - "6379:6379"
    networks:
      - ab_network
    volumes:
      - type: volume
        source: redis_data
        target: /data
    
  database:
    container_name: postgres
    image: postgres:16.1-alpine
    restart: unless-stopped
    env_file:
      - ./Presentation/env/postgres.env
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432" # If you have a local postgres instance running, you may need to change host port
    networks:
      - ab_network

networks:
  ab_network:

volumes:
  redis_data:
  postgres_data: